### ISSUE TITLE
How many times to polish an assembly

### ISSUE THREAD

**Issue by romseg** [institut-de-genomique/HAPO-G#14]
Dear author,

I am wondering if it's recommended to polish an assembly more than once consecutively to get the best results with Hapo-G? Or once is enough? In my case I assembled my plant diploid genome with Canu using Nanopore data sequenced on R9.4.1 pores and basecalled with Guppy 4.0.11; and I have ~250X assembly coverage with 150PE Illumina data for polishing with Hapo-G. Thank you.

Romulo

**Comment by bistace** [comment]
Hello,

for the polishing phase, we recommend the following:
  - one time using Racon and Nanopore reads
  - one time using Medaka and Nanopore reads
  - two times using Hapog and Illumina reads

This gave us the best results on most genomes.

**Comment by romseg** [comment]
I will follow your recommendations. Thanks for your help.

Romulo

**Comment by bishopia** [comment]
If one had Illumina and Hifi reads, do you have any recommendations on polishing round order and number? Based on your recommendation above, it seems plausible to run Racon with Hifi once then Hapog twice with Illumina. You also mention a 6 round polishing at the end of your manuscript, but I wasn't clear on the order (3 hifi rounds followed by 3 illumina round maybe?). Any help much appreciated. -ian

**Comment by bistace** [comment]
Hello,

if your assembly was made with hicanu or hifiasm, I don't think that a polishing step is required because your assembly will already reach Q45-Q50 with HiFi reads alone. I may be wrong there because we did not investigate the impact of polishing on HiFi assemblies but that is what I observe on our own data.

If you want to try it if you think that it could be beneficial for the quality of your assembly, I think that doing one polishing with hapog and Illumina reads and one polishing with hapog and HiFi reads would probably lead to the most results. 

In the manuscript, we tried up to 6 rounds to see if there were any significant changes in quality but the only real gains occured before 2 rounds of polishing. I don't think that this amount of polishing steps (I mean the 6 rounds) will ever be needed to achieve a great genome assembly quality.
