### ISSUE TITLE
Docs question: what does the -u option do?

### ISSUE THREAD

**Issue by cabbagesofdoom** [institut-de-genomique/HAPO-G#4]
Hi,

Please can you explain the difference in behaviour to be expected with and without the option:

```
-u                          # Include unpolished sequences in the output
```

Thanks,

Rich

**Comment by bistace** [comment]
Hi,

let's imagine that you assembled a genome and obtained two contigs: Contig_A and Contig_B. Now let's also imagine that for some reasons, Contig_A is not covered by any Illumina reads. In this case, Hapo-G will be able to polish contig_B but not Contig_A, since there is no coverage.

By default, Hapo-G will not include Contig_A in the output file because it was not able to correct it. If you specify the `-u` flag, Hapo-G will include Contig_A in the output, even though it is uncorrected.

**Comment by cabbagesofdoom** [comment]
Thanks. It might be worth clarifying that in the description a bit. I know from my experience (and Twitter!) with Racon that many/most people assume a polisher will output all the input sequences, so if this is the default setting then it would be a good idea to add a big warning message at the end of the run if any sequences are excluded due to low coverage.

**Comment by bistace** [comment]
Thank you for your feedback, we will try to make it more explicit. However, you should be careful with Racon, because it also needs a `-u` flag to output unpolished sequence (see [racon usage](https://github.com/lbcb-sci/racon#usage))
